import type { PageBlockTree } from '../builder-schema';

export function createArticleTemplateTree(): PageBlockTree {
  return {
    version: 2,
    rootIds: ['article-section'],
    nodes: {
      'article-section': {
        id: 'article-section',
        type: 'section',
        name: 'Article',
        parentId: null,
        children: ['article-cover-wrap', 'article-header-wrap', 'article-body-wrap'],
        content: {},
        styles: {
          backgroundColor: '#f8fafc',
          paddingTop: '92px',
          paddingBottom: '96px',
          paddingLeft: '24px',
          paddingRight: '24px',
        },
        responsiveStyles: {
          tablet: { paddingTop: '82px' },
          mobile: { paddingTop: '74px', paddingBottom: '64px', paddingLeft: '16px', paddingRight: '16px' },
        },
      },
      'article-cover-wrap': {
        id: 'article-cover-wrap',
        type: 'container',
        name: 'Cover container',
        parentId: 'article-section',
        children: ['article-cover'],
        content: {},
        styles: {
          maxWidth: '1200px',
          marginLeft: 'auto',
          marginRight: 'auto',
          width: '100%',
          textAlign: 'center',
        },
      },
      'article-cover': {
        id: 'article-cover',
        type: 'image',
        name: 'Cover image',
        parentId: 'article-cover-wrap',
        children: [],
        content: {
          src: '/images/hero-wetland.webp',
          alt: 'Article cover',
          objectFit: 'cover',
          bindings: {
            src: { source: 'record', path: 'coverImageUrl', fallback: '/images/hero-wetland.webp', format: 'image' },
            alt: { source: 'record', path: 'title', fallback: 'Article cover', format: 'text' },
          },
        },
        styles: {
          width: '80%',
          aspectRatio: '16/9',
          borderRadius: '20px',
          marginLeft: 'auto',
          marginRight: 'auto',
          display: 'block',
        },
        responsiveStyles: {
          tablet: { width: '90%' },
          mobile: { width: '100%', borderRadius: '14px' },
        },
      },
      'article-header-wrap': {
        id: 'article-header-wrap',
        type: 'container',
        name: 'Article header',
        parentId: 'article-section',
        children: ['article-title', 'article-date', 'article-share'],
        content: {},
        styles: {
          position: 'relative',
          zIndex: 9,
          maxWidth: '960px',
          marginTop: '-80px',
          marginLeft: 'auto',
          marginRight: 'auto',
          width: '100%',
          backgroundColor: '#ffffff',
          borderRadius: '4px 4px 0 0',
          paddingTop: '56px',
          paddingBottom: '20px',
          paddingLeft: '64px',
          paddingRight: '64px',
        },
        responsiveStyles: {
          mobile: {
            marginTop: '-40px',
            paddingTop: '28px',
            paddingBottom: '16px',
            paddingLeft: '20px',
            paddingRight: '20px',
          },
        },
      },
      'article-title': {
        id: 'article-title',
        type: 'heading',
        name: 'Article title',
        parentId: 'article-header-wrap',
        children: [],
        content: {
          text: 'Article title',
          tag: 'h1',
          bindings: { text: { source: 'record', path: 'title', fallback: 'Article title' } },
        },
        styles: {
          fontFamily: 'Neue Montreal, sans-serif',
          fontSize: '32px',
          fontWeight: 400,
          lineHeight: '1.2',
          textAlign: 'left',
          textColor: '#1e293b',
          marginBottom: '16px',
        },
        responsiveStyles: { mobile: { fontSize: '26px' } },
      },
      'article-date': {
        id: 'article-date',
        type: 'paragraph',
        name: 'Publication date',
        parentId: 'article-header-wrap',
        children: [],
        content: {
          html: '<p>December 16, 2025</p>',
          text: 'December 16, 2025',
          bindings: { html: { source: 'record', path: 'publishedAt', fallback: '', format: 'date' } },
        },
        styles: {
          fontFamily: 'Neue Montreal, sans-serif',
          fontSize: '13px',
          textAlign: 'left',
          textColor: '#64748b',
          marginBottom: '20px',
        },
      },
      'article-share': {
        id: 'article-share',
        type: 'social-share',
        name: 'Article sharing',
        parentId: 'article-header-wrap',
        children: [],
        content: {
          title: 'Article',
          url: '',
          buttonSize: 32,
          borderRadius: 4,
          gap: 10,
          alignment: 'left',
          bindings: {
            title: { source: 'record', path: 'title', fallback: 'Envint article' },
            url: { source: 'route', path: 'absoluteUrl', fallback: 'https://envintglobal.com/' },
          },
        },
        styles: { width: '100%' },
      },
      'article-body-wrap': {
        id: 'article-body-wrap',
        type: 'container',
        name: 'Article body container',
        parentId: 'article-section',
        children: ['article-body'],
        content: {},
        styles: {
          maxWidth: '960px',
          marginLeft: 'auto',
          marginRight: 'auto',
          width: '100%',
          backgroundColor: '#ffffff',
          borderRadius: '0 0 4px 4px',
          paddingLeft: '64px',
          paddingRight: '64px',
          paddingBottom: '56px',
        },
        responsiveStyles: {
          mobile: {
            paddingLeft: '20px',
            paddingRight: '20px',
            paddingBottom: '36px',
          },
        },
      },
      'article-body': {
        id: 'article-body',
        type: 'rich-text',
        name: 'Article body',
        parentId: 'article-body-wrap',
        children: [],
        content: {
          html: '<p>This section displays dynamic article content loaded from your CMS Insights database for each article. In this shared template, you can customize the layout, typography, colors, and margins that apply across all articles.</p>',
          bindings: { html: { source: 'record', path: 'contentHtml', fallback: '', format: 'html' } },
        },
        styles: {
          fontFamily: 'Neue Montreal, sans-serif',
          fontSize: '18px',
          lineHeight: '1.85',
          textColor: '#334155',
        },
      },
    },
  };
}
